server:
  servlet:
    context-path: /ccapi
  port: 8081

spring:
  datasource:
    username: mx
    password: mx
    url: jdbc:sqlite::resource:db/db.sqlite
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      schema-locations: classpath:db/schema.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.relaxcg.ccapi.repository.dao: debug